import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Post() {
  return (
    <div className={styles.postcontainer}>
      <Head>
        <title>DeGods Alpha</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className={styles.titlepost}>How to use Candy Machine & Arweave to Mint Your Own NFT Collection</h1>
        <p>Written by @degods123</p>
      </div>
      <div>
        <p>
          <p>
            Solana has a lot to offer for everyone interested in the NFT
            movement. It&rsquo;s cheap transaction fees and incredible speed
            makes minting a very smooth experience and makes it accessible to
            everyone. This also drives crazy innovations and you would be
            surprised by the quality&nbsp;
          </p>
          <p>
            Solana NFT space is still young and in a period of rapid growth and
            development. With so many new projects being minted every single day
            it can be hard to navigate through this space.&nbsp;
          </p>
          <p>
            If you are an ETH veteran looking for cheap gas, or an NFT newbie
            who just entered the space - let me show you around.
          </p>
          <p>
            Let&rsquo;s start with the basics for all those new people around
            here - without them you are definitely ngmi.
          </p>
          <ul>
            <li>
              Crypto Twitter -&gt; the best source of information and primary
              communication channel. Follow Projects you are interested in
              minting, quality influencers accounts.&nbsp;
            </li>
            <li>
              Discord -&gt; most projects are building strong communities here -
              usually major announcements drop there first.
            </li>
          </ul>
          <p>
            If you are interested in the project join their discord and engage
            the community - it can go a long way
          </p>
          <p>
            Having that taken care of let&rsquo;s move to the tools that you can
            use to understand the space better. Everyone in crypto is familiar
            with sites like CoinMarketCap or CoinGecko where you can track
            performance of cryptocurrencies, but what can be used for NFT?
          </p>
          <p>Let&rsquo;s start with analytics:</p>
          <ul>
            <li>
              Sonanalysis - one of the best data aggregator in SOL NFT space.
            </li>
          </ul>
          <p>
            Track the performance of all of the major NFT projects (floor price
            &amp; volume changes, twitter followers)
          </p>
          <p>Check the list of upcoming NFT mints</p>
          <ul>
            <li>
              Solanafloor - Wet dream for every data geek out there. Full of
              useful analytics on key metrics in NFT and the best tool to
              understand trends. You can analyse not only the whole collection
              but also your selection based on traits you are looking for.
            </li>
          </ul>
          <p>How many of minted token are currently listed on marketplaces</p>
          <p>
            Number of owners - token distribution over time &amp; whale tracker
          </p>
          <p>Price evolution &amp; distribution across rank</p>
          <p>
            Let&rsquo;s not forget that the marketplaces themselves can offer a
            great deal of insight as well. You can analyze the floor for the
            collection or particular traits by filtering, checking the price
            history, and some offer also aggregated statistics for listed
            collections.
          </p>
          <ul>
            <li>
              Solanart - 3% MP fee, support buy now &amp; bidding (soon).
              Provides basic statistics for listed collections (24h/7d) as well
              as chart tracking sales &amp; average price per collection
            </li>
            <li>
              Magic Eden - 2% MP fee, support buy &amp; bidding. Provides basic
              statistics for listed collections (24h/7d/30d)
            </li>
            <li>
              Alpha Art - 1.4% MP fee, supports buy now &amp; bidding. No extra
              statistics
            </li>
            <li>
              DigitalEyes - flat 0.01 SOL fee, support only buy now. No extra
              statistics
            </li>
            <li>
              Solsea - 3% MP fee, supports buy now &amp; bidding (soon). No
              extra statistics
            </li>
          </ul>
          <p>
            Before you run out to the marketplace and start buying random pieces
            there is one more thing that it&rsquo;s worth to understand.
            Aesthetics play a big role, but rarity is crucial to understand the
            potential value of the NFT. Using rarity tools can ensure you are
            getting the best bang for your buck.
          </p>
          <p>
            One watchout though - all rarity tools have their own logic on how
            they aggregate rarity of all traits so the ranking may slightly
            differ.
          </p>
          <p>
            Here you can find a list of most trusted rarity tools. They all
            provide similar functionality for rarities but have different extra
            features
          </p>
          <ul>
            <li>
              MoonRank - you can connect your wallet and check ranks for your
              whole collection
            </li>
            <li>HowRare.is - extra section for upcoming NFT drops</li>
            <li>
              RarityMon - extra section for upcoming NFT drops, supports ETH as
              well
            </li>
          </ul>
          <p>
            Now you should be well equipped to start minting &amp; sniping your
            favourite collection.
          </p>
          <p>
            Once you&rsquo;re done and want to flex your NFT collection here are
            sites that will help you with that:
          </p>
          <p>
            Solanalysis - Show off you NFT collection with estimated value (only
            for projects listed on solanalysis)
          </p>
          <p>
            NFT Eyez - Show off your NFT collection &amp; generate the collage
            (useful if you you are JPG whale)
          </p>
          <p>
            At the end I want to share with you few additional resources that
            may help you navigate through this space:
          </p>
          <ul>
            <li>
              EveryTimeZone.com - every project announces their mint date at
              different time zones. This will help you to understand what that
              mean for you
            </li>
          </ul>
          <ul>
            <li>
              Solana Explorer / Solbeach / Solscan - track your transactions and
              everything on the blockchain
            </li>
          </ul>
          <p>Welcome to Solana and good luck!</p>
        </p>
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by DeGods
        </a>
      </footer>
    </div>
  );
}
