import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Post() {
  return (
    <div className={styles.postcontainer}>
      <Head>
        <title>DeGods Alpha</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<div>
  <p>
    coming soon
  </p>
</div>
    

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by DeGods
        </a>
      </footer>
    </div>
  );
}
