import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Navbar from '../components/Navbar';

import Link from 'next/link';

export default function Home() {
    return (
        <div>
            <div className={styles.navdiv}>
            <Navbar></Navbar>
            </div>
            <div className={styles.container}>
                <Head>
                    <title>by DeGods</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/degodslogo.png" />
                </Head>

                <main className={styles.main}>
                    <Image src="/dexyz.png" alt="logo" height={100} width={300} objectFit="contain" />
                   
                    <p className={styles.description}>Solana NFT resources from the biggest brains in the metaverse.</p>

                    <div className={styles.grid}>
                        <Link href="/post">
                            <a className={styles.imagecard}>

                                
                               
                                <Image src="/comingsoon/navigating.png" alt="logo" height={290} width={290} objectFit="contain" />
                                <h2 className={styles.postheading}>How to Read the Solana Blockchain</h2>
                              
                            </a>
                        </Link>
                     
                        <Link href="/" >
                     
                            <a className={styles.imagecard}>
                           
                            <Image src="/comingsoon/unicorn.png" alt="logo" height={290} width={290} objectFit="contain" />

                                <h2 className={styles.postheading}>Rarity Sniper Discord Bot</h2>
                               
                               
                            </a>
                        </Link>

                        <Link href="/">
                            <a className={styles.imagecard}>
                           
                            <Image src="/comingsoon/resources.png" alt="logo" height={290} width={290} objectFit="contain" />
                                <h2 className={styles.postheading}>Useful SOL NFT resources </h2>
                              
                            </a>
                        </Link>

                        <Link href="/" >
                       
                            <a className={styles.imagecard}>
                           
                            <Image src="/comingsoon/marketplace.png" alt="logo" height={290} width={290} objectFit="contain" />
                                <h2 className={styles.postheading}>Analysis of Solana NFT Marketplaces</h2>
                            
                            </a>
                        </Link>

                        <Link href="/" >
                    
                            <a className={styles.imagecard}>
                           
                            <Image src="/comingsoon/candymachine.png" alt="logo" height={290} width={290} objectFit="contain" />
                                <h2 className={styles.postheading}>How to Use Candy Machine</h2>
                               
                              
                            </a>
                        </Link>
                        <Link href="/" >
                     
                            <a className={styles.imagecard}>
                           
                            <Image src="/comingsoon/buy_nft.png" alt="logo" height={290} width={290} objectFit="contain" />
                                <h2 className={styles.postheading}>How To Buy Solana NFTs for Dummies</h2>
                          
                            </a>
                        </Link>
                        <Link href="/" >
                      
                            <a className={styles.imagecard}>
                           
                            <Image src="/comingsoon/mintingrare.png" alt="logo" height={290} width={290} objectFit="contain" />
                                <h2 className={styles.postheading}>Tips on Increasing Chances to Mint a Hype Project</h2>
                             
                            </a>
                        </Link>
                        <Link href="/" >
                       
                            <a className={styles.imagecard}>
                           
                            <Image src="/comingsoon/attributes.png" alt="logo" height={290} width={290} objectFit="contain" />
                                <h2 className={styles.postheading}>Understand Valuable Attributes Beyond Ranking</h2>
                               
                              
                            </a>
                        </Link>
                        <Link href="/" >
                      
                            <a className={styles.imagecard}>
                           
                            <Image src="/comingsoon/arverse.png" alt="logo" height={290} width={290} objectFit="contain" />
                                <h2 className={styles.postheading}>Creating Your Own Personal 3D AR Metaverse</h2>
                              
                              
                            </a>
                        </Link>
                        <Link href="/" >
                     
                            <a className={styles.imagecard}>
                           
                            <Image src="/comingsoon/commonvsrare.png" alt="logo" height={290} width={290} objectFit="contain" />
                                <h2 className={styles.postheading}>Analysis on Buying Floors vs. Rares</h2>
                             
                               
                            </a>
                        </Link>
                    </div>
                </main>

                <footer className={styles.footer}>
                <a
                    style={{ color: '#000', textDecoration: 'none'}}
                        href="https://degods.com"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        Powered by DeGods
                    </a>
                </footer>
            </div>
        </div>
    );
}
