import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Post.module.css';
import Navbar from '../components/Navbar';
import SendSol from '../components/SendSol';
import Notification from '../components/Notification';
import { useState } from 'react';

export default function Post() {
    const [signature, setSignature] = useState('');


    return (
        <div>
            <Navbar></Navbar>

            <div className={styles.postcontainer}>
                <div>
                    <Head>
                        <title>DeGods Alpha</title>
                        <meta name="description" content="Generated by create next app" />
                        <link rel="icon" href="/degodslogo.png" />
                    </Head>
                </div>

                <div>
                    <h1 className={styles.titlepost}>Understanding the Solana Block Explorer for NFTs</h1>
                    <Image src="/headerpic.jpg" alt="post1-1" height={600} width={800} objectFit="contain" />

                    <div className={styles.author}>
                        <Image
                            src="/degodspfp.png"
                            alt="post1-1"
                            height={50}
                            width={50}
                            className={styles.authoricon}
                            // objectFit="contain"
                        />

                        <p className={styles.authorname}>@degods123</p>

                        <div>
                            <SendSol setSignature={setSignature} />
                        </div>

                        <p>
                            <strong>Twitter</strong>
                        </p>
                    </div>

                    <p>All of these magic .jpegs we’re buying on the internet have something special about them.</p>
                    <p>
                        They are on the blockchain. So, knowing how the blockchain works is going to give you an edge in
                        understanding what’s happening under the hood with your NFTs.
                    </p>

                    <p>
                        You can do this and more by using the{' '}
                        <a href="https://explorer.solana.com/" target="_blank" rel="noopener noreferrer">
                            Solana Explorer
                        </a>
                        ; a tool created by the Solana team to navigate through the Solana Blockchain.
                    </p>

                    <p>
                        The best way to learn is by using specific examples. So let’s start by gathering the NFT address
                        and uncovering the mint price.
                    </p>

                    <h2> Finding your NFT </h2>

                    <p> To do anything on Solana Explorer, you will need some sort of address.</p>

                    <ol>
                        <li>Click the triple dots on your NFT in Phantom and click “View on Explorer.”</li>

                        <div className={styles.imagecontainer}>
                            <Image
                                src="/post1/image11.png"
                                alt="post1-1"
                                height={300}
                                width={300}
                                objectFit="contain"
                            />
                            <span style={{ marginTop: 20 }}> Alpha Art&apos;s Listing of DeGod #3467</span>
                        </div>

                        <li>
                            Copy the <strong> Mint Address </strong>
                        </li>

                        <div className={styles.blockquote}>
                            <strong> Mint Address: </strong> This is the unique identifier for an NFT
                        </div>

                        <div className={styles.imagecontainer}>
                            {/* <div style={{borderRadius: 20, overflow: 'hidden', borderWidth: 3, border: '1px #FFF'}}> */}
                            <Image
                                src="/post1/image9.png"
                                alt="post1-1"
                                height={400}
                                width={600}
                                className={styles.imageround}
                                // style={{borderRadius: 20}}
                                objectFit="cover"
                            />
                            {/* </div> */}
                            <span style={{ marginTop: 20 }}> Screenshot of an NFT in a phantom wallet </span>
                        </div>

                        <div className={styles.imagecontainer}>
                            <Image src="/post1/image2.png" alt="post1-1" height={100} width={600} objectFit="contain" />
                            {/* <span style={{ marginTop: 20 }}>   Address: BgEuh9thWSsWNfSLzqtZozqfEj9CzQwsDXuQaC8bAyTP</span> */}

                            <a
                                href="https://alpha.art/t/BgEuh9thWSsWNfSLzqtZozqfEj9CzQwsDXuQaC8bAyTP"
                                target="_blank"
                                rel="noopener noreferrer"
                            >
                                Screenshot of an NFT in a phantom wallet
                            </a>

                            <span style={{ marginTop: 20 }}>
                                {' '}
                                Mint Addresses are usually used on Marketplaces for individual NFT page URLs
                            </span>
                        </div>

                        <li>
                            <p>
                                You are looking at this <strong> NFT’s Block Explorer Page </strong>
                            </p>
                        </li>

                        <div className={styles.imagecontainer}>
                            <Image src="/post1/image1.png" alt="post1-1" height={500} width={600} objectFit="contain" />

                            <a style={{ marginTop: 20 }}> Solana Explorer Page of DeGod #3467</a>
                        </div>
                    </ol>

                    <p>
                        {' '}
                        Now with this information, <strong> we can find the mint cost. </strong>
                    </p>

                    <h2>Finding the Mint Cost</h2>

                    <ol>
                        <li>Click the History Tab</li>
                        <li>Scroll to the first transaction (the most bottom one)</li>
                        <li>
                            Click the <strong> transaction signature </strong>
                        </li>
                    </ol>

                    <div className={styles.imagecontainer}>
                        <Image src="/post1/image10.png" alt="post1-1" height={600} width={600} objectFit="contain" />
                        <span style={{ marginTop: 20 }}> Screenshot of an NFT in a phantom wallet </span>
                    </div>

                    <p>The “Account Inputs” section lists all information about this Mint Transaction. </p>

                    <p>
                        In the first line, the highlighted pink value,
                        <code> -◎3.0119812</code>, is the amount of SOL that the original minter spent on this NFT.
                    </p>

                    <p>
                        The <strong> Post Balance </strong> for their wallet after this mint was
                        <code>◎3.19274064</code> which means they had 6.2 SOL in their wallet before this mint.
                    </p>

                    <p>
                        Then, we see that the address starting with <code> AXFuni...</code> got <code>+◎3.</code>{' '}
                    </p>

                    <p>
                        <strong>Boom, 3 SOL. That&apos;s the official mint price.</strong>
                    </p>

                    <h2>Finding the Current NFT Holder</h2>

                    <ol>
                        <li>Go back to the NFT Block Explorer Page</li>
                        <li>Go to the most recent Transaction Signature in the History tab</li>
                        <li>Scroll down and find Token: Initialize Account</li>
                        <li>The Owner in this section is the current holder of this NFT</li>
                    </ol>

                    <div className={styles.imagecontainer}>
                        <Image src="/post1/image6.png" alt="post1-1" height={200} width={600} objectFit="contain" />
                        <span style={{ marginTop: 20 }}> Screenshot of an NFT in a phantom wallet </span>
                    </div>

                    <h2>Understanding The NFT Sale</h2>

                    <p>
                        <strong>Listings</strong>
                    </p>

                    <p>
                        If an NFT is listed, this means that the NFT isn’t currently in any one person’s “wallet”. It is
                        being held in an escrow account (kind of like a middleman), so if someone buys it, they can get
                        it immediately.
                    </p>

                    <p>Once it is sold, a program executes and sends the Lister SOL & sends the Buyer the NFT.</p>

                    <p>
                        Look at how the timestamps for the listing & sale align with the Block Explorer and the
                        Marketplace.
                    </p>

                    <div className={styles.imagecontainer}>
                        <Image src="/post1/image4.png" alt="post1-1" height={150} width={600} objectFit="contain" />
                        <span style={{ marginTop: 20 }}> Screenshot of an NFT in a phantom wallet </span>
                    </div>

                    <div className={styles.imagecontainer}>
                        <Image src="/post1/image5.png" alt="post1-1" height={150} width={600} objectFit="contain" />
                        <span style={{ marginTop: 20 }}> Screenshot of an NFT in a phantom wallet </span>
                    </div>

                    <p>
                        The bottom transaction that starts with 4Crak... is the Transaction that lists the NFT on the
                        marketplace.
                    </p>

                    <p>Search for “Token: Set Authority” to find where the important details are.</p>

                    <div className={styles.imagecontainer}>
                        <Image src="/post1/image7.png" alt="post1-1" height={300} width={600} objectFit="contain" />
                        {/* <span style={{ marginTop: 20 }}>  Screenshot of an NFT in a phantom wallet </span> */}
                    </div>

                    <ul>
                        <li>Account: the shared escrow wallet that’s created to store the listed NFT</li>
                        <li>NewAuthority: The marketplace’s wallet</li>
                        <li>Signers #1: Wallet authorizing this Instruction</li>
                    </ul>

                    <h2>The Sale</h2>

                    <ol>
                        <li>Navigate to the transaction that starts with 4VPiQuw6dmvc</li>
                        <li>Account Inputs will show all the information we need to know about sales.</li>
                    </ol>

                    <div className={styles.imagecontainer}>
                        <Image src="/post1/image8.png" alt="post1-1" height={600} width={600} objectFit="contain" />
                        <span style={{ marginTop: 20 }}> Screenshot of an NFT in a phantom wallet </span>
                    </div>

                    <ol>
                        <li>Wallet uses ◎6.00204428 to purchase this item</li>
                        <li>Collect ◎0.00203928 for gas to help move the NFT</li>
                        <li>
                            The Shared Wallet that held the NFT in the marketplace moves the NFT to the buyer using
                            ◎0.00203928 for gas
                        </li>
                        <li>Seller gains ◎5.74566096 tax (Service fee + Royalty fee is already subtracted)</li>
                        <li>
                            Signer and Account that was created for listing closes the account with ◎0.00162168 (This
                            was given in the listing by the Seller)
                        </li>

                        <li>Skip</li>
                        <li>Marketplace’s wallet gains ◎0.084 (Service fee)</li>
                        <li>Skip</li>
                        <li>Skip</li>
                        <li>NFT Creator’s wallet gains ◎0.174 (Royalty fee)</li>
                    </ol>

                    <h2>Tracking the Journey to your wallet</h2>

                    <p>
                        Knowing all this, you can track the journey of any NFT from mint to marketplace listing to a
                        sale to your wallet.
                    </p>

                    <p>
                        I went ahead and highlighted each action in the Transaction History, so please verify by using
                        the skills you’ve learned.
                    </p>

                    <div className={styles.imagecontainer}>
                        <Image
                            src="/post1/image3.png"
                            alt="post1-1"
                            //layout="fixed"

                            height={500}
                            width={600}
                            objectFit="contain"
                            //objectFit="cover"
                        />
                        <span style={{ marginTop: 20 }}> Screenshot of an NFT in a phantom wallet </span>
                    </div>

                    <p>
                        Solana Explorer is an incredible tool that the Solana team provided, so put it to good use and
                        honestly all the information is out there. Everything you’ve learned in this article can help
                        you verify sketchy listings, track where funds/NFTs go, and track anything that goes on in the
                        Solana block chain. I want you to stay safe from scams, have some great laughs, and see you use
                        this new found knowledge to navigate through this incredible Solana Ecosystem.
                    </p>

                    <p>Knowledge is power, my friends. Cheers 🍻.</p>

                    {/* <h2>Questions</h2> */}
                    {/* <p>What are the few ways to find the Address of an NFT?</p>
        <p>A. Wallet &rarr; Explorer &rarr; Mint Address&nbsp;</p>
        <p>
          B. Go to marketplace &rarr; Search # &rarr; copy long thing after
          the forward slash (/)
        </p>
        <p>
          C. Go to Solana Explorer &rarr; Paste in your NFT&rsquo;s name
          &rarr; copy long thing after the forward slash (/)
        </p>
        <p>
          D. Go to marketplace &rarr; Search # &rarr; copy the value address
          in &ldquo;To&rdquo; from the Trading History
        </p>
        <p>How do you find out where a NFT is living?&nbsp;</p>
        <p>
          A. Go to the NFT address &rarr; click on the latest transaction
          &rarr; it&rsquo;s the &ldquo;Owner&rdquo; line in &ldquo;Token:
          Initialize Account&rdquo;
        </p>
        <p>
          B. Go to the NFT address &rarr; click on &ldquo;Update
          Authority&rdquo; &rarr;&nbsp; it&rsquo;s the value in &ldquo;Address
        </p>
        <p>
          C. Go to the NFT address &rarr; click into the earliest transaction
          &rarr; it&rsquo;s the first address in &ldquo;Account
          Input(s)&rdquo;
        </p>
        <p>
          D. Go to the NFT address &rarr; click into &ldquo;Mint
          Authority&rdquo; &rarr; it&rsquo;s the first address in Transaction
        </p>
        <p>How do you find out how much something was minted for?</p>
        <p>
          A. Go to the NFT address &rarr; click the earliest Transaction
          &rarr; it&rsquo;s the first SOL value in &ldquo;Account
          Input(s)&rdquo;
        </p>
        <p>
          B. Go to the NFT address &rarr; click the earliest Transaction
          &rarr; it&rsquo;s the second SOL value in &ldquo;Account
          Input(s)&rdquo;
        </p>
        <p>
          C. Go to the NFT address, on the latest Transaction &rarr;
          it&rsquo;s the second SOL value in &ldquo;Account Input(s)&rdquo;
        </p>
        <p>
          D. Go to the NFT address, on the latest Transaction &rarr;
          it&rsquo;s the first SOL value in &ldquo;Account Input(s)&rdquo;
        </p>
        <p>How do you find out the first owner of a NFT?</p>
        <p>
          A. Go to the NFT address &rarr; click into the earliest Transaction
          &rarr; it&rsquo;s the first address in &ldquo;Account
          Input(s)&rdquo;
        </p>
        <p>
          B. Go to the NFT address &rarr; click into the latest Transaction
          &rarr; it&rsquo;s the second address in &ldquo;Account
          Input(s)&rdquo;
        </p>
        <p>
          C. Go to the NFT address &rarr; click into the latest Transaction
          &rarr; it&rsquo;s the first address in &ldquo;Account
          Input(s)&rdquo;
        </p>
        <p>
          D. Go to the NFT address &rarr; click into the latest Transaction
          &rarr; it&rsquo;s the second address in &ldquo;Account
          Input(s)&rdquo;
        </p>
        <p>Should I use a burner wallet for mints and marketplaces?</p>
        <p>A. Yes</p>
        <p>B. Yes</p>
        <p>C. Yes</p>
        <p>D. Yes</p> */}
                </div>

                <footer className={styles.footer}>
                    <a
                        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        Powered by DeGods
                    </a>
                </footer>
            </div>
            {signature && signature !== '' ? <Notification signature={signature} /> : null}
        </div>
    );
}
