import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Post() {
  return (
    <div className={styles.postcontainer}>
      <Head>
        <title>DeGods Alpha</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Rarity Sniper Discord Bot</h1>
        <p>Written by @degods123</p>
      </div>
      <main>
        <h1>
          Frank’s Proposed Outline: Release the actual code by integrating into
          DeGods Discord Release a blog post that breaks down the process.
        </h1>

        <p>
          Which rarity system do you use? Explain in a short few sentences the
          rarity calculations you are using. What parameters would you set to
          “trigger” the Rarity Sniper to post to the webhook - basically explain
          what’s your threshold for the sniper. Why would someone use this /
          what value does it provide How can another project reach out to you
          and pay you to get this set up on their Discord
        </p>
      </main>

      {/* <a href="/" className={styles.card}>
            <h2>How to Read the Solana Blockchain</h2>
            <p>Written by @degods123</p>
          </a> */}

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by DeGods
          {/* <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span> */}
        </a>
      </footer>
    </div>
  );
}
